=== dejik/Xml_Project1/InfoBoxSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.wikipedia.org/InfoaBoxSchema" xmlns:tns="http://www.wikipedia.org/InfoaBoxSchema" elementFormDefault="qualified">

    <element name="InfoBox" type="tns:InfoBox"></element>
    
    <complexType name="InfoBox">
    	<sequence>
    		<element name="Author" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="OrginalTitle" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="Display" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="Language " type="tns:elementType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="Genre" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="PubDate" type="tns:elementType" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="pages" type="integer" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="elementType">
    	<sequence>
    		<element name="Name" type="string"></element>
    	</sequence>
    	<attribute name="scheme" type="string"></attribute>
    </complexType>
</schema>

=== dejik/Xml_Project1/InfoBoxInstance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:InfoBox xmlns:tns="http://www.wikipedia.org/InfoaBoxSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wikipedia.org/InfoaBoxSchema InfoBoxSchema.xsd ">
  <tns:Author>John.Doe</tns:Author>
  <tns:OrginalTitle>String_Extract </tns:OrginalTitle>
  <tns:Display>String_Extract</tns:Display>
  <tns:Languade scheme="rTF566467">
    <tns:Name>en-US</tns:Name>
  </tns:Languade>
  <tns:Genre>Tutoral</tns:Genre>
  <tns:publisher>JavaPoint </tns:publisher>
  <tns:PubDate scheme="W3C-10">
    <tns:Name>2010-10</tns:Name>
  </tns:PubDate>
  <tns:pages>400</tns:pages>
</tns:InfoBox>

=== dejik/Xml_Project1/InfoBoxInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:InfoBox xmlns:tns="http://www.wikipedia.org/InfoaBoxSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wikipedia.org/InfoaBoxSchema InfoBoxSchema.xsd ">
  <tns:Author>Erik T. Ray</tns:Author>
  <tns:OrginalTitle>LearningXml</tns:OrginalTitle>
  <tns:Display>LearningXml</tns:Display>
  <tns:Languade scheme="rTF56646">
    <tns:Name>en-US</tns:Name>
  </tns:Languade>
  <tns:Genre>Tutorial</tns:Genre>
  <tns:publisher>XmlTeach</tns:publisher>
  <tns:PubDate scheme="W3C-09">
    <tns:Name>2001-09</tns:Name>
  </tns:PubDate>
  <tns:pages>401</tns:pages>
</tns:InfoBox>
